name: trip-wise
services:
  - name: web
    environment_slug: python
    github:
      branch: backend
      deploy_on_push: true
      repo: leanhdung0505/tripwise-backend
    build_command: pip install -r requirements.txt
    run_command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envs:
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/v1/utils/health-check
